#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
#targetType=libso
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

./src/Allclean

wclean ./applications/utilities/preProcessing/canteraToFPVFoamV301
wclean ./applications/utilities/postProcessing/FPVFoamV301Post
wclean ./applications/solver/FPVFoamV301

# ----------------------------------------------------------------- end-of-file
