#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

./src/Allclean

wclean $targetType applications/utilities/preProcessing/canteraToFPVFoamV30
wclean $targetType applications/utilities/postProcessing/FPVFoamV30Post
wclean $targetType applications/solver/FPVFoamV30

# ----------------------------------------------------------------- end-of-file
