#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

./src/Allwmake

wmake  ./applications/utilities/preProcessing/canteraToFPVFoamV301
wmake  ./applications/utilities/postProcessing/FPVFoamV301Post
wmake  ./applications/solver/FPVFoamV301

# ----------------------------------------------------------------- end-of-file
