+ ./src/Allwmake
+ wmake libso ./thermophysicalModels/specie
'/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV301specie.so' is up to date.
+ wmake libso ./thermophysicalModels/basic
'/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV301fluidThermophysicalModels.so' is up to date.
+ wmake libso ./thermophysicalModels/reactionThermo
'/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV301reactionThermophysicalModels.so' is up to date.
+ wmake libso ./thermophysicalModels/chemistryModel
'/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV301chemistryModel.so' is up to date.
+ wmake libso ./TurbulenceModels/turbulenceModels
'/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV301turbulenceModels.so' is up to date.
+ wmake libso ./TurbulenceModels/compressible
g++ -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I../turbulenceModels/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/basic/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/thermophysicalModels/specie/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/thermophysicalModels/solidSpecie/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/finiteVolume/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OSspecific/POSIX/lnInclude   -fPIC -c turbulentFluidThermoModels/turbulentFluidThermoModels.C -o Make/linux64GccDPInt32Opt/turbulentFluidThermoModels/turbulentFluidThermoModels.o
In file included from ../turbulenceModels/lnInclude/kEpsilon.H:212:0,
                 from turbulentFluidThermoModels/turbulentFluidThermoModels.C:67:
../turbulenceModels/lnInclude/kEpsilon.C:27:23: fatal error: fvOptions.H: No such file or directory
 #include "fvOptions.H"
                       ^
compilation terminated.
make: *** [Make/linux64GccDPInt32Opt/turbulentFluidThermoModels/turbulentFluidThermoModels.o] Error 1
+ wmake libso ./fvOptions
make: *** No rule to make target `Make/linux64GccDPInt32Opt/sources/general/codedSource/codedSource.C.dep', needed by `Make/linux64GccDPInt32Opt/sources/general/codedSource/codedSource.o'.  Stop.
+ wmake libso ./combustionModels
g++ -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/basic/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/reactionThermo/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/compressible/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/finiteVolume/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OSspecific/POSIX/lnInclude   -fPIC -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/combustionModel/combustionModel.o Make/linux64GccDPInt32Opt/rhoCombustionModel/rhoCombustionModel/rhoCombustionModel.o Make/linux64GccDPInt32Opt/rhoCombustionModel/rhoCombustionModel/rhoCombustionModelNew.o Make/linux64GccDPInt32Opt/rhoCombustionModel/rhoThermoCombustion/rhoThermoCombustion.o Make/linux64GccDPInt32Opt/rhoCombustionModel/rhoChemistryCombustion/rhoChemistryCombustion.o Make/linux64GccDPInt32Opt/flameletTable/linearInterpolation/linearInterpolation.o Make/linux64GccDPInt32Opt/flameletTable/flameletTable/flameletTable.o Make/linux64GccDPInt32Opt/flameletTable/tableSolver/tableSolver.o Make/linux64GccDPInt32Opt/YSLFModel/YSLFModels.o -L/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/platforms/linux64GccDPInt32Opt/lib \
	    -L/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib -lcompressibleTransportModels -lFPVFoamV301turbulenceModels -lFPVFoamV301compressibleTurbulenceModels -lchemistryModel -lfiniteVolume -lmeshTools  -o /home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV30CombustionModels.so
/usr/bin/ld: cannot find -lFPVFoamV301compressibleTurbulenceModels
collect2: error: ld returned 1 exit status
make: *** [/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib/libFPVFoamV30CombustionModels.so] Error 1
+ wmake ./applications/utilities/preProcessing/canteraToFPVFoamV301
g++ -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/finiteVolume/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/compressible/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/Gamma.o Make/linux64GccDPInt32Opt/canteraScanner.o Make/linux64GccDPInt32Opt/canteraReader.o Make/linux64GccDPInt32Opt/canteraToFPVFoamV301.o -L/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/platforms/linux64GccDPInt32Opt/lib \
	    -L/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib -lODE -lcompressibleTransportModels -lFPVFoamV301fluidThermophysicalModels -lFPVFoamV301specie -lFPVFoamV301chemistryModel -lFPVFoamV301CombustionModels -lFPVFoamV301reactionThermophysicalModels -lFPVFoamV301turbulenceModels -lFPVFoamV301compressibleTurbulenceModels -lfiniteVolume -lmeshTools -lOpenFOAM -ldl  \
	     -lm -o /home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/bin/canteraToFPVFoamV301
/usr/bin/ld: cannot find -lFPVFoamV301CombustionModels
collect2: error: ld returned 1 exit status
make: *** [/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/bin/canteraToFPVFoamV301] Error 1
+ wmake ./applications/utilities/postProcessing/FPVFoamV301Post
g++ -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/finiteVolume/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/meshTools/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/combustionModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/chemistryModel  -IlnInclude -I. -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/FPVFoamV301Post.o -L/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/platforms/linux64GccDPInt32Opt/lib \
	    -L/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/lib -lODE -lFPVFoamV301specie -lcompressibleTransportModels -lFPVFoamV301fluidThermophysicalModels -lFPVFoamV301reactionThermophysicalModels -lFPVFoamV301CombustionModels -lFPVFoamV301chemistryModel -lFPVFoamV301turbulenceModels -lFPVFoamV301compressibleTurbulenceModels -lfiniteVolume -lmeshTools -lsampling -lOpenFOAM -ldl  \
	     -lm -o /home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/bin/FPVFoamV301Post
/usr/bin/ld: cannot find -lFPVFoamV301CombustionModels
collect2: error: ld returned 1 exit status
make: *** [/home/weixian001/OpenFOAM/weixian001-3.0.1/platforms/linux64GccDPInt32Opt/bin/FPVFoamV301Post] Error 1
+ wmake ./applications/solver/FPVFoamV301
g++ -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/TurbulenceModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/basic/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/finiteVolume/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/meshTools/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/sampling/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/thermophysicalModels/chemistryModel -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/ODE/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam-v3.0.1/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OpenFOAM/lnInclude -I/usr/local/RH6_apps/OpenFOAM/OpenFOAM-3.0.1/src/OSspecific/POSIX/lnInclude   -fPIC -c FPVFoamV301.C -o Make/linux64GccDPInt32Opt/FPVFoamV301.o
FPVFoamV301.C:42:23: fatal error: fvOptions.H: No such file or directory
 #include "fvOptions.H"
                       ^
compilation terminated.
make: *** [Make/linux64GccDPInt32Opt/FPVFoamV301.o] Error 1
